### ISSUE TITLE
Color scheme in Kotlin is botched

### ISSUE THREAD

**Issue by abc123098123** [Vincent-P/gruvbox-intellij-theme#43]
This plugin is pretty great, since it provides the gruvbox color scheme to the whole IDE.
But unfortunately, when using Kotlin, the color scheme seems botched, not conveying the beauty of the theme.

1. Common keywords referring to function declaration (`fun`, `override`, `suspend`, etc) are in orange when, IMO, they should be in gruvbox red.

2. When defining the value of function parameters, the color is a blue that is not even part of gruvbox:
![image](https://user-images.githubusercontent.com/2325589/96515365-1942d180-125d-11eb-80fb-815435479fb8.png)

What do you think?

**Comment by Vincent-P** [comment]
Hello,
Keywords should be red, maybe you have conflicts with other themes?
Blue should be Gruvbox blue indeed.

**Comment by abc123098123** [comment]
Hey!

Well, about the blue, it is not gruvbox blue, correct me if I am wrong. The blue in that image is `#467CDA`' which does not exist in the color scheme.

![image](https://user-images.githubusercontent.com/2325589/99528627-79c94980-2996-11eb-81f5-3c4255592b9b.png)

The keywords weren't red because they were inherited from Java Keyword color, which is Orange "#CC7832".

But you are correct, these values don't even exist in this repository. How can I detect conflicts with other themes? Because I am not using anything else, nor I installed any other themes.

**Comment by Vincent-P** [comment]
The keywords should be red, do you have other themes installed or enabled?
![image](https://user-images.githubusercontent.com/10779205/99534281-74282f80-29a7-11eb-80f5-8b8c3f0b4fe5.png)

I fixed the blue color this morning in https://github.com/Vincent-P/gruvbox-intellij-theme/commit/1ad416308a62826c95f615c373841422e334dcc0, the update will be released soon in the marketplace.

**Comment by abc123098123** [comment]
Hey, thanks for the update!

Well, I have these installed:

![image](https://user-images.githubusercontent.com/2325589/99537944-31188d00-29a4-11eb-9127-8fd6fa03e147.png)

Only 1 theme. 

This seems to be some conflict here, because uninstalling and installing does not fix anything.. After reinstalling this is what appears in the Kotlin color Scheme:

![image](https://user-images.githubusercontent.com/2325589/99538518-f9f6ab80-29a4-11eb-925d-ce9401a8bc98.png)

**Comment by Vincent-P** [comment]
Maybe you have local changes, can you click on the gear icon and "Reset Defaults"?

**Comment by abc123098123** [comment]
Yeah, just did that, unfortunately colors are still messed up :-S
I'll just change them myself. I'll try to deal with this later.

Thanks!

**Comment by sid-6581** [comment]
I had the same issue. For some reason the Java keyword color wasn't inherited from language defaults, so all I had to do was check that checkbox. Not sure why it was unchecked.

**Comment by GabrielCoteM** [comment]
I came here to report this, but it only happens in Android Studio for me, not in IntelliJ Ultimate. It might be related to Android Studio in that case.

**Comment by GabrielCoteM** [comment]
> I had the same issue. For some reason the Java keyword color wasn't inherited from language defaults, so all I had to do was check that checkbox. Not sure why it was unchecked.

Doing that for each inheritable color values was what fixed it for me, in both Java and Kotlin. Thanks!

**Comment by GabrielCoteM** [comment]
The problem also applies to the Go language in Goland, and the same fix can be applies on there as well.
